const etudiantData = [
    {
        keys: 1,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 2,
        id_user: "1",
        nom: "Sylla",
        prenom: "Hawa",
        sexe: "F",
        date_naissance: "02/12/1987",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 3,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 4,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 5,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 6,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 7,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 8,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 9,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    },
    {
        keys: 10,
        id_user: "1",
        nom: "Johnson",
        prenom: "Moise",
        sexe: "M",
        date_naissance: "02/12/2003",
        matricule: "2100626",
        photo: require("../images/Saved_Pictures/sung_Jinhou.jpg"),
        user_: "tonio",
        mot_de_passe: "12345678",
        universite_id: 1,
        adresse_id: 2
    }
]

export default etudiantData;